apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: Example
spec:
  entrypoint: d
  imagePullSecrets:
  - name: gh-registry
  serviceAccountName: argo-workflow
  templates:
  - dag:
      tasks:
      - name: flip
        template: flip
      - depends: flip
        name: heads
        template: heads
        when: '{{tasks.flip.outputs.result}} == heads'
      - depends: flip
        name: tails
        template: tails
        when: '{{tasks.flip.outputs.result}} == tails'
    name: d
  - name: flip
    script:
      command:
      - python
      image: ghcr.io/aiknow-public/hera-blueprint-base:main
      imagePullPolicy: Always
      source: 'import os

        import sys

        sys.path.append(os.getcwd())

        import random

        from art import art

        art_1 = art(''foo'')

        print(art_1)

        result = ''heads'' if random.randint(0, 1) == 0 else ''tails''

        print(result)'
  - name: heads
    script:
      command:
      - python
      image: python:3.8
      source: 'import os

        import sys

        sys.path.append(os.getcwd())

        print(''it was the heads'')'
  - name: tails
    script:
      command:
      - python
      image: python:3.8
      source: 'import os

        import sys

        sys.path.append(os.getcwd())

        print(''it was tails'')'
