apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: Example
spec:
  entrypoint: d
  imagePullSecrets:
  - name: gh-registry
  serviceAccountName: argo-workflow
  templates:
  - dag:
      tasks:
      - name: foo
        template: foo
    name: d
  - name: foo
    script:
      command:
      - python
      image: ghcr.io/aiknow-public/hera-blueprint-base:main
      imagePullPolicy: Always
      source: 'import os

        import sys

        sys.path.append(os.getcwd())

        import random

        from art import art

        art_1 = art(''foo'')

        print(art_1)'
