apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: Example
spec:
  entrypoint: d
  imagePullSecrets:
  - name: gh-registry
  serviceAccountName: argo-workflow
  templates:
  - dag:
      tasks:
      - name: foo
        template: foo
    name: d
  - name: foo
    script:
      command:
      - python
      image: ghcr.io/aiknow-public/hera-blueprint:sha256:631b8e767320d05ace50631be9cac064261a426deb83c1eaabfb8df1a7625192
      imagePullPolicy: Always
      source: 'import os

        import sys

        sys.path.append(os.getcwd())

        from art import art

        from some_tasks import do_something

        do_something()

        art_1 = art(''foo'')

        print(art_1)'
