apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hera-example-animals
  namespace: playground
spec:
  entrypoint: d
  serviceAccountName: argo-workflow
  templates:
  - dag:
      tasks:
      - name: foo
        template: foo
    name: d
  - name: foo
    script:
      command:
      - python
      image: ghcr.io/aiknow-public/hera-blueprint:1.0.0
      imagePullPolicy: Always
      source: 'import os

        import sys

        sys.path.append(os.getcwd())

        from art import art

        from samplemodule import do_something

        do_something()

        art_1 = art(''foo'')

        print(art_1)'
