apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hera-example
spec:
  entrypoint: d
  serviceAccountName: argo-workflow
  templates:
  - dag:
      tasks:
      - name: foo
        template: foo
    name: d
  - name: foo
    script:
      command:
      - python
      image: artifactory.boschdevcloud.com/gs-pj-top98-ai-know/hera-blueprint:sha-6d0987b
      imagePullPolicy: Always
      source: 'import os

        import sys

        sys.path.append(os.getcwd())

        from art import art

        from samplemodule import do_something

        do_something()

        art_1 = art(''foo'')

        print(art_1)'
