name: Create / Update Pull Request for QA deployment

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Build and Deploy to Dev"]
    types:
      - completed

jobs:
  update_qa_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        if: steps.find_pr.outputs.pull_request_number == ''
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          base: qa
          title: Merge main into qa
          body: Automated pull request creation