name: Create / Update Pull Request for QA deployment

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Build and Deploy to Dev"]
    types:
      - completed

jobs:
  createPullRequest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Checkout and update 'qa' branch
        run: |
          git checkout -B qa
          git pull origin main --no-edit

      - name: Create or Update PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Merge main into qa"
          branch: "qa"
          base: "main"
          delete-branch: false
          body: "Update qa branch with changes from main."