name: Create / Update Pull Request for QA deployment

# Only trigger, when the build workflow succeeded
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Deploy to Dev"]
    types:
      - completed

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: create pull request
        run: gh pr create -B qa -H main --title 'Deploy to QA' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}