name: Create / Update Pull Request for QA deployment

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Build and Deploy to Dev"]
    types:
      - completed

jobs:
  create_or_update_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install reviewdog
        run: |
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $(go env GOPATH)/bin

      - name: Find Pull Request
        id: find_pr
        run: |
          pr_number=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository }}:${{ github.ref }}&base=qa" | \
            jq -r '.[0].number')
          echo "::set-output name=pr_number::$pr_number"

      - name: Create or Update Pull Request
        run: |
          pr_number=${{ steps.find_pr.outputs.pr_number }}
          if [ -n "$pr_number" ]; then
            echo "Updating existing Pull Request #$pr_number"
            reviewdog -f=diff -name="pullrequest" -reporter="github-pr-review" \
              -filter-mode="added" -tee -level=info \
              -diff="git diff --name-only --diff-filter=ACMRTUXB ${{ github.event.before }}...${{ github.sha }}" \
              -fail-on-error="$pr_number"
          else
            echo "Creating new Pull Request"
            reviewdog -f=diff -name="pullrequest" -reporter="github-pr-check" \
              -filter-mode="added" -tee -level=info \
              -diff="git diff --name-only --diff-filter=ACMRTUXB ${{ github.event.before }}...${{ github.sha }}"
          fi