name: Create / Update Pull Request for QA deployment

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Build and Deploy to Dev"]
    types:
      - completed

jobs:
  createPullRequest:
    runs-on: ubuntu-latest

    steps:
      - name: Create or Update PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Merge main into qa"
          branch: "qa"
          base: "main"
          delete-branch: false
          body: "Update qa branch with changes from main."